- hosts: localhost
  roles:
    - apache
    - icinga
    - grafana
    - role: postgresql
      dbname: icingaweb2
      dbuser: icingaweb2
      dbpass: "{{ lookup('password', '/dev/null length=32') }}"
