- name: Enable icingaweb2 conf
  shell: a2enconf icingaweb2
  args:
    creates: /etc/apache2/conf-enabled/icingaweb2.conf
  notify: Restart Apache 

- name: Configure date.timezone in PHP
  lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: '^;{,1}date\.timezone ='
    line: 'date.timezone = Europe/Prague'
  notify: Restart Apache
