- name: Install Icinga2 packages
  apt:
    name: "{{ item }}"
    state: present 
    default_release: stretch-backports
  with_items:
    - icinga2
    - icingaweb2
    - icinga2-ido-pgsql
    - icingacli

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php-gd
    - php-imagick
    - php-intl
    - php-pgsql
  notify: Restart Apache
