- name: Install Icinga2 packages
  apt:
    name: "{{ pkgs }}"
    state: present 
    default_release: stretch-backports
  vars:
    pkgs:
      - icinga2
      - icinga2-ido-pgsql
      - icingacli
      - icingaweb2
      - icingaweb2-module-monitoring

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php-gd
    - php-imagick
    - php-intl
    - php-pgsql
    - php-curl
  notify: Restart Apache
